# Generated by Django 3.0.3 on 2020-02-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200225_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='teamMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.TeamMember'),
        ),
    ]
