# Generated by Django 3.0.3 on 2020-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200225_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
